### ISSUE TITLE
Fix google scholar script action

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/brainglobe-web#2]
I've added a [script](https://github.com/brainglobe/brainglobe-web/blob/main/scripts/scraper.py) which searches google scholar for papers citing brainglobe's work to automatically update the references page ('citing brainglobe' page: https://brainglobe.info/references). 
A github [action](https://github.com/brainglobe/brainglobe-web/blob/main/.github/workflows/update_references.yml) runs the script automatically. Currently it runs on `push`, but a `scheduler` can be used to have it run automatically once a day (see: https://jasonet.co/posts/scheduled-actions/).

There's a couple issues:
- [x] scholarly doesnt seem to work on github actions for some reason. That's kinda important so we need a workaround
- [x] all hits on google scholars are added to the list, including brainglobe's own papers and papers that cite them but don't actually use these tools.
- [x] Currently just the title and link are there. We have additional bibliography information like authors, journal.. What do we want to have? @adamltyson

**Comment by FedeClaudi** [comment]
Also this page: https://docs.brainglobe.info/bg-atlasapi/work-using-brainglobes-tools could be since we have the equivalent at https://brainglobe.info/references

**Comment by FedeClaudi** [comment]
This might help https://github.com/scholarly-python-package/scholarly/issues/222

**Comment by FedeClaudi** [comment]
Running github actions for updating websites works in general, including with scheduling to run it e.g. on a weekly basis:

action: https://github.com/FedeClaudi/FedeClaudi.github.io/actions/runs/1000372950/workflow
updated page: https://fedeclaudi.github.io/refy.html

**Comment by FedeClaudi** [comment]
I've switched from using google scholar to semantic scholar which has an API that works on github actions. 
The only problem is that it doesn't support keyword searching like in google scholar.
So instead I've looked up all publications from the three of us (@adamltyson  & @vigji) and then filtered for papers belonging to brainglobe. I then use this to pull the papers citing brainglobe's papers and add them to the markdown.

The github action now runs correctly and it's scheduled to run on a weekly basis (on Monday morning, 8am UK time).

Thoughts?

**Comment by adamltyson** [comment]
I think I'm happy with it the way it is, one page listing BrainGlobe papers for reference, and another, automatically generated, list of citing papers (which will end up including some of ours).

https://brainglobe.info/references seems to have quite a few papers missing though? Maybe those are the papers citing either preprints, or zenodo DOIs?

**Comment by FedeClaudi** [comment]
It was missing brainrender's paper so I've changed things so that it finds it. It currently selects from our papers those that have some [keywords](https://github.com/brainglobe/brainglobe-web/blob/2f5b11d863e16587756e5d4a139a25fde3cad37e/scripts/scraper.py#L20) in the abstract, that should work right?
I also don't know if it captures for instance citation's of brainrender's preprint and then the eLife paper.

**Comment by adamltyson** [comment]
I can't see a pattern TBH. I just checked my profile on both, some papers have more, and other have fewer citations. It doesn't seem related to the age of the citation.

**Comment by FedeClaudi** [comment]
yeah, weird. So we either have something with google scholar running locally on someone's machine or if we want to use actions it has to be semantic scholar. I'm happy with the latter

**Comment by adamltyson** [comment]
Yeah, I'm fine with it too. There certainly isn't a "best" service. There's also microsoft academic, and that also gets another, seemingly random, subset of papers.

**Comment by adamltyson** [comment]
Closing this for now as we've abandoned this. Maybe we can revisit sometime.
