### ISSUE TITLE
BrainGlobe Website V2

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainglobe-web#6]
At the moment relevant information is scattered around:
* brainglobe.info
* docs.brainglobe.info
* docs.brainrender.info
* Various GitHub repos
* Papers

Ideally all BGI information should be in a single place. https://napari.org/ is a good example.

**Comment by adamltyson** [comment]
To aid maintainability this should use Sphinx & (potentially a fork of) the pydata theme. This is what we're doing in the NIU (see [cookiecutter PR](https://github.com/neuroinformatics-unit/python-cookiecutter/pull/30), [main site](https://neuroinformatics.dev/) and a [sample docs site](https://datashuttle.neuroinformatics.dev/). Ideally NIU and BrainGlobe should use the same tech, deployment process etc.

The NIU docs are currently deployed using GitHub actions. readthedocs should simplify this slightly (e.g. no need to maintain a branch for GH pages), and allow for versioned docs (a `dev` version for unreleased code would be ideal). @dstansby will investigate deployment with RTD and we will compare to GitHub pages. 

RTD allows [custom (sub)domains](https://docs.readthedocs.io/en/stable/custom-domains.html#custom-domains) so we should have everything we need.

@dstansby has started work on a branch at https://github.com/dstansby/cellfinder-core/tree/api-doc

Once the structure of the docs is in place, @adamltyson will copy and proofread material from brainglobe.info and docs.brainglobe.info

cc @niksirbi @lauraporta

**Comment by niksirbi** [comment]
Sounds good. It's a direction I thought of taking anyway with the NIU sites.
Once the first working example via RTD is up, let me know and I will happily implement it on the NIU websites.

**Comment by adamltyson** [comment]
Started over at https://github.com/brainglobe/new-website
